version: 2.1

commands:
  command_1:
    parameters:
      VAR:
        type: string
    steps:
      - run: echo $VAR

jobs:
  job_1:
    docker:
      - image: cimg/base:stable
    steps:
      # no print anything
      - run: echo $VAR
      - command_1:
          VAR: $VAR

      # no print anything
      - run: |
          VAR="can you see?"
      - run: echo $VAR
      - command_1:
          VAR: $VAR

      # no print anything
      - run: |
          export VAR="can you see?"
      - run: echo $VAR
      - command_1:
          VAR: $VAR

workflows:
  workflow_1:
    jobs:
      - job_1
