version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.2.0

jobs:
  job_1:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
  job_2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - shellcheck/install
      - run:
          command: shellcheck --help
          name: Run Shellcheck command


workflows:
  workflow_1:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - job_1
      - job_2
  workflow_2:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ daily_build, << pipeline.schedule.name >> ]
    jobs:
      - job_1
      - job_2
  workflows_3:
    triggers:
      - schedule:
          cron: "40 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - job_1
      - job_2
