version: 2.1

jobs:
  job_1:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
  job_2:
    docker:
      - image: circleci/node:latest
    parameters:
      hoge:
        type: string
        default: foo
    steps:
      - checkout
      - run: echo << parameters.hoge >>
      - run: echo << parameters.hoge >>>
      - run: echo \<<< parameters.hoge >>
      - run: echo \<<< parameters.hoge >>>
      # - run: echo <<< parameters.hoge >> # <- validation error
      # - run: echo <<< parameters.hoge >>> # <- validation error

workflows:
  workflow_1:
    jobs:
      - job_1
      - job_2
  workflow_2:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ daily_build, << pipeline.schedule.name >> ]
    jobs:
      - job_1
      - job_2
